package com.example.report.excel;

import com.example.exception.general.FileOperationException;
import com.example.model.record.CountryOfOriginReportRow;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

@Component
public class CountryOfOriginExcelBuilder {
  private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Hong_Kong");

  private static final DateTimeFormatter REPORT_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEEE, MMM dd yyyy", Locale.ENGLISH);
  private static final DateTimeFormatter REPORT_GENERATED_ON_FORMAT =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

  private static final String[] HEADERS = {"Country", "Total", "Bookings"};

  public byte[] build(
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      List<CountryOfOriginReportRow> rows) {
    try (Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
      String sheetName =
          startDate + "-Report-" + UUID.randomUUID().toString().replace("-", "").substring(0, 13);
      Sheet sheet = workbook.createSheet(sheetName.substring(0, Math.min(sheetName.length(), 31)));

      ZonedDateTime generatedAt = ZonedDateTime.now(REPORT_ZONE);
      int rowIndex = writeMetadata(sheet, startDate, endDate, generatedBy, generatedAt);

      writeHeaderRow(sheet, rowIndex++);

      long totalPassengers = 0;
      long totalBookings = 0;
      for (CountryOfOriginReportRow row : rows) {
        writeDataRow(sheet, rowIndex++, row);
        totalPassengers += row.totalPassengers();
        totalBookings += row.bookingCount();
      }

      writeTotalRow(sheet, rowIndex, totalPassengers, totalBookings);

      for (int columnIndex = 0; columnIndex < HEADERS.length; columnIndex++) {
        sheet.autoSizeColumn(columnIndex);
      }

      workbook.write(outputStream);
      return outputStream.toByteArray();
    } catch (IOException e) {
      throw new FileOperationException("Failed to generate country of origin report");
    }
  }

  private int writeMetadata(
      Sheet sheet,
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      ZonedDateTime generatedAt) {
    int row = 2;
    createValueRow(sheet, row++, "DEMOGRAPHICS - COUNTRY OF ORIGIN");
    row++;
    createValueRow(sheet, row++, "Report Start Date:");
    createValueRow(sheet, row++, startDate.format(REPORT_DATE_FORMAT));
    createValueRow(sheet, row++, "Report End Date:");
    createValueRow(sheet, row++, endDate.format(REPORT_DATE_FORMAT));
    createValueRow(sheet, row++, "Report Generated On:");
    createValueRow(
        sheet, row++, generatedAt.withZoneSameInstant(REPORT_ZONE).format(REPORT_GENERATED_ON_FORMAT));
    createValueRow(sheet, row++, "Generated By:");
    createValueRow(sheet, row++, generatedBy != null ? generatedBy : "System");
    row++;
    return row;
  }

  private void writeHeaderRow(Sheet sheet, int rowIndex) {
    Row row = sheet.createRow(rowIndex);
    for (int i = 0; i < HEADERS.length; i++) {
      row.createCell(i).setCellValue(HEADERS[i]);
    }
    ReportExcelStyles.applyGreyToEntireRow(row, HEADERS.length, true);
  }

  private void writeDataRow(Sheet sheet, int rowIndex, CountryOfOriginReportRow row) {
    Row excelRow = sheet.createRow(rowIndex);
    excelRow.createCell(0).setCellValue(formatCountryName(row.countryCode()));
    excelRow.createCell(1).setCellValue(row.totalPassengers());
    excelRow.createCell(2).setCellValue(row.bookingCount());
  }

  private void writeTotalRow(
      Sheet sheet, int rowIndex, long totalPassengers, long totalBookings) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(1).setCellValue(totalPassengers);
    row.createCell(2).setCellValue(totalBookings);
    ReportExcelStyles.applyGreyToEntireRow(row, HEADERS.length, true);
  }

  private void createValueRow(Sheet sheet, int rowIndex, String value) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue(value);
    ReportExcelStyles.applyGreyToEntireRow(row, HEADERS.length, false);
  }

  static String formatCountryName(String countryCode) {
    if (countryCode == null || countryCode.isBlank()) {
      return "Unknown";
    }
    String normalized = countryCode.trim();
    if (normalized.length() == 2) {
      String displayName =
          new Locale("", normalized.toUpperCase(Locale.ROOT)).getDisplayCountry(Locale.ENGLISH);
      if (displayName != null && !displayName.isBlank()) {
        return displayName;
      }
    }
    return normalized;
  }
}
