package com.example.report.excel;

import com.example.exception.general.FileOperationException;
import com.example.model.record.ExpiredGiftCertificateCodesReportRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

@Component
public class ExpiredGiftCertificateCodesExcelBuilder {
  private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Hong_Kong");

  private static final DateTimeFormatter REPORT_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEEE, MMM dd yyyy", Locale.ENGLISH);
  private static final DateTimeFormatter REPORT_GENERATED_ON_FORMAT =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

  private static final DateTimeFormatter EXPIRY_DATE_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy");

  private static final String[] HEADERS = {
    "Type",
    "GC ID",
    "Online Code",
    "Status",
    "Wholesale Value",
    "Retail Value",
    "Expiry",
    "Purchaser Name",
    "Description",
    "Balance"
  };

  public byte[] build(
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      List<ExpiredGiftCertificateCodesReportRow> rows) {
    try (Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
      String sheetName =
          startDate + "-Report-" + UUID.randomUUID().toString().replace("-", "").substring(0, 13);
      Sheet sheet = workbook.createSheet(sheetName.substring(0, Math.min(sheetName.length(), 31)));

      ZonedDateTime generatedAt = ZonedDateTime.now(REPORT_ZONE);
      int rowIndex = writeMetadata(sheet, startDate, endDate, generatedBy, generatedAt);

      writeHeaderRow(sheet, rowIndex++);

      BigDecimal totalWholesale = BigDecimal.ZERO;
      BigDecimal totalRetail = BigDecimal.ZERO;
      BigDecimal totalBalance = BigDecimal.ZERO;
      for (ExpiredGiftCertificateCodesReportRow row : rows) {
        writeDataRow(sheet, rowIndex++, row);
        totalWholesale = totalWholesale.add(nullToZero(row.wholesaleValue()));
        totalRetail = totalRetail.add(nullToZero(row.retailValue()));
        totalBalance = totalBalance.add(nullToZero(row.balance()));
      }

      writeTotalRow(sheet, rowIndex, totalWholesale, totalRetail, totalBalance);

      for (int columnIndex = 0; columnIndex < HEADERS.length; columnIndex++) {
        sheet.autoSizeColumn(columnIndex);
      }

      workbook.write(outputStream);
      return outputStream.toByteArray();
    } catch (IOException e) {
      throw new FileOperationException("Failed to generate expired gift certificate codes report");
    }
  }

  private int writeMetadata(
      Sheet sheet,
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      ZonedDateTime generatedAt) {
    int row = 2;
    createValueRow(sheet, row++, "ALL EXPIRED GIFT CERTIFICATES");
    row++;
    createValueRow(sheet, row++, "Report Start Date:");
    createValueRow(sheet, row++, startDate.format(REPORT_DATE_FORMAT));
    createValueRow(sheet, row++, "Report End Date:");
    createValueRow(sheet, row++, endDate.format(REPORT_DATE_FORMAT));
    createValueRow(sheet, row++, "Report Generated On:");
    createValueRow(
        sheet, row++, generatedAt.withZoneSameInstant(REPORT_ZONE).format(REPORT_GENERATED_ON_FORMAT));
    createValueRow(sheet, row++, "Generated By:");
    createValueRow(sheet, row++, generatedBy != null ? generatedBy : "System");
    row++;
    return row;
  }

  private void writeHeaderRow(Sheet sheet, int rowIndex) {
    Row row = sheet.createRow(rowIndex);
    for (int i = 0; i < HEADERS.length; i++) {
      row.createCell(i).setCellValue(HEADERS[i]);
    }
  }

  private void writeDataRow(Sheet sheet, int rowIndex, ExpiredGiftCertificateCodesReportRow row) {
    Row excelRow = sheet.createRow(rowIndex);
    excelRow.createCell(0).setCellValue(row.typeLabel());
    excelRow.createCell(1).setCellValue(row.giftCertificateRefNo());
    excelRow.createCell(2).setCellValue(row.promoCode());
    excelRow.createCell(3).setCellValue(row.statusLabel());
    setNumericCell(excelRow.createCell(4), row.wholesaleValue());
    setNumericCell(excelRow.createCell(5), row.retailValue());
    if (row.expiryDate() != null) {
      excelRow.createCell(6).setCellValue(row.expiryDate().format(EXPIRY_DATE_FORMAT));
    }
    if (row.purchaserName() != null && !row.purchaserName().isBlank()) {
      excelRow.createCell(7).setCellValue(row.purchaserName());
    }
    if (row.description() != null) {
      excelRow.createCell(8).setCellValue(row.description());
    }
    setNumericCell(excelRow.createCell(9), row.balance());
  }

  private void writeTotalRow(
      Sheet sheet, int rowIndex, BigDecimal totalWholesale, BigDecimal totalRetail, BigDecimal totalBalance) {
    Row row = sheet.createRow(rowIndex);
    setNumericCell(row.createCell(4), totalWholesale);
    setNumericCell(row.createCell(5), totalRetail);
    setNumericCell(row.createCell(9), totalBalance);
  }

  private void createValueRow(Sheet sheet, int rowIndex, String value) {
    sheet.createRow(rowIndex).createCell(0).setCellValue(value);
  }

  private void setNumericCell(Cell cell, BigDecimal value) {
    if (value != null) {
      cell.setCellValue(value.doubleValue());
    }
  }

  private BigDecimal nullToZero(BigDecimal value) {
    return value != null ? value : BigDecimal.ZERO;
  }
}
