package com.example.report.excel;

import com.example.exception.general.FileOperationException;
import com.example.model.record.PromoCodesByTransactionDateReportRow;
import com.example.repository.ReportDataRepository;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;

@Component
public class PromoCodesByTransactionDateExcelBuilder {
  private static final String DEFAULT_ACTIVITY_PROVIDER = "Hong Kong Tramways";
  private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Hong_Kong");

  private static final DateTimeFormatter REPORT_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEEE, MMM d yyyy", Locale.ENGLISH);
  private static final DateTimeFormatter REPORT_DAY_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy");
  private static final DateTimeFormatter TRANSACTION_DATE_TIME_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
  private static final DateTimeFormatter REPORT_GENERATED_ON_FORMAT =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
  private static final DateTimeFormatter ACTIVITY_TIME_FORMAT =
      DateTimeFormatter.ofPattern("h:mma", Locale.ENGLISH);

  private static final String[] HEADERS = {
    "Conf.#",
    "Transaction Date/Time",
    "Activity Date",
    "Activity Name",
    "Guest Name",
    "Passengers",
    "Activity Total",
    "Activity Provider",
    "Promo Name",
    "Promo Rate Type",
    "Promo Rate",
    "Discount($)"
  };

  public byte[] build(
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      List<PromoCodesByTransactionDateReportRow> rows,
      Map<Long, List<ReportDataRepository.TicketQuantityRow>> ticketQuantitiesByBookingEventId) {
    try (Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
      String sheetName =
          startDate + "-Promo-" + UUID.randomUUID().toString().replace("-", "").substring(0, 10);
      Sheet sheet = workbook.createSheet(sheetName.substring(0, Math.min(sheetName.length(), 31)));

      List<String> ticketTypeNames =
          TicketTypePassengerColumns.collectTicketTypeNamesFromMap(ticketQuantitiesByBookingEventId);
      String[] headers = TicketTypePassengerColumns.expandHeaders(HEADERS, ticketTypeNames);

      ZonedDateTime generatedAt = ZonedDateTime.now(REPORT_ZONE);
      writeMetadata(sheet, startDate, endDate, generatedBy, generatedAt, headers.length);

      int headerRowIndex = 18;
      writeHeaderRow(sheet, headerRowIndex, headers);

      int rowIndex = headerRowIndex + 1;
      PromoTotals totals = new PromoTotals(ticketTypeNames);

      for (PromoCodesByTransactionDateReportRow row : rows) {
        List<ReportDataRepository.TicketQuantityRow> ticketRows =
            ticketQuantitiesByBookingEventId.getOrDefault(row.bookingEventId(), List.of());
        writeDataRow(sheet, rowIndex++, row, ticketRows, ticketTypeNames, totals);
      }

      writeTotalRow(sheet, rowIndex, headers.length, ticketTypeNames, totals);

      for (int columnIndex = 0; columnIndex < headers.length; columnIndex++) {
        sheet.autoSizeColumn(columnIndex);
      }

      workbook.write(outputStream);
      return outputStream.toByteArray();
    } catch (IOException e) {
      throw new FileOperationException("Failed to generate gift certificate codes by transaction date report");
    }
  }

  private void writeMetadata(
      Sheet sheet,
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      ZonedDateTime generatedAt,
      int columnCount) {
    int row = 2;
    createLabelValueRow(sheet, row++, "GIFT CERTIFICATE CODES BY TRANSACTION DATE", null, columnCount);
    row++;
    createLabelValueRow(sheet, row++, "Report Start Date:", startDate.format(REPORT_DATE_FORMAT), columnCount);
    createLabelValueRow(sheet, row++, "Report End Date:", endDate.format(REPORT_DATE_FORMAT), columnCount);
    createLabelValueRow(
        sheet,
        row++,
        "Report Generated On:",
        generatedAt.withZoneSameInstant(REPORT_ZONE).format(REPORT_GENERATED_ON_FORMAT),
        columnCount);
    createLabelValueRow(
        sheet, row++, "Generated By:", generatedBy != null ? generatedBy : "System", columnCount);
    row++;
  }

  private void writeHeaderRow(Sheet sheet, int rowIndex, String[] headers) {
    Row row = sheet.createRow(rowIndex);
    for (int i = 0; i < headers.length; i++) {
      row.createCell(i).setCellValue(headers[i]);
    }
    ReportExcelStyles.applyGreyToEntireRow(row, headers.length, true);
  }

  private void writeDataRow(
      Sheet sheet,
      int rowIndex,
      PromoCodesByTransactionDateReportRow row,
      List<ReportDataRepository.TicketQuantityRow> ticketRows,
      List<String> ticketTypeNames,
      PromoTotals totals) {
    BigDecimal activityTotal = nullToZero(row.eventSubtotal());
    BigDecimal discount = allocatedDiscount(row);

    Row excelRow = sheet.createRow(rowIndex);
    int column = 0;
    setTextCell(excelRow, column++, row.bookingRefNo());
    setTransactionDateTimeCell(excelRow, column++, row.transactionDateTime());
    setDateCell(excelRow, column++, row.eventDate());
    excelRow.createCell(column++).setCellValue(formatActivityName(row));
    excelRow.createCell(column++).setCellValue(formatGuestName(row));
    column = TicketTypePassengerColumns.writeQuantities(excelRow, column, ticketTypeNames, ticketRows);
    setMoneyCell(excelRow, column++, activityTotal);
    excelRow.createCell(column++).setCellValue(DEFAULT_ACTIVITY_PROVIDER);
    excelRow.createCell(column++).setCellValue(nullToBlank(row.promoCode()));
    excelRow.createCell(column++).setCellValue(resolvePromoRateType(row));
    setMoneyCell(excelRow, column++, resolvePromoRate(row, activityTotal, discount));
    setMoneyCell(excelRow, column++, discount);

    totals.add(ticketRows, discount);
  }

  private void writeTotalRow(
      Sheet sheet,
      int rowIndex,
      int columnCount,
      List<String> ticketTypeNames,
      PromoTotals totals) {
    int passengerStartColumn = 5;
    int discountColumn =
        passengerStartColumn
            + (ticketTypeNames.isEmpty() ? 1 : ticketTypeNames.size())
            + 5;

    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue("Total");
    TicketTypePassengerColumns.writeTotals(
        row, passengerStartColumn, ticketTypeNames, totals.passengersByTicketType);
    setMoneyCell(row, discountColumn, totals.discount);
    ReportExcelStyles.applyGreyToEntireRow(row, columnCount, true);
  }

  private void createLabelValueRow(
      Sheet sheet, int rowIndex, String label, String value, int columnCount) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue(label);
    if (value != null) {
      row.createCell(1).setCellValue(value);
    }
    ReportExcelStyles.applyGreyToEntireRow(row, columnCount, false);
  }

  private String formatActivityName(PromoCodesByTransactionDateReportRow row) {
    String englishName = nullToBlank(row.eventName());
    if (!englishName.isBlank()) {
      return englishName;
    }
    if (row.eventTime() == null || row.eventTime().isBlank()) {
      return "";
    }
    return parseEventTime(row.eventTime())
        .format(ACTIVITY_TIME_FORMAT)
        .toLowerCase(Locale.ENGLISH);
  }

  private String formatGuestName(PromoCodesByTransactionDateReportRow row) {
    String firstName = nullToBlank(row.guestFirstName());
    String lastName = nullToBlank(row.guestLastName());
    return (firstName + " " + lastName).trim();
  }

  private String resolvePromoRateType(PromoCodesByTransactionDateReportRow row) {
    String type = nullToBlank(row.giftCertificateType());
    if ("VALUE".equalsIgnoreCase(type)) {
      return "OPEN";
    }
    if ("EVENT".equalsIgnoreCase(type)) {
      return "ACTIVITY";
    }
    if ("PERCENT".equalsIgnoreCase(type)) {
      return "PERCENT";
    }
    return type;
  }

  private BigDecimal resolvePromoRate(
      PromoCodesByTransactionDateReportRow row, BigDecimal activityTotal, BigDecimal discount) {
    BigDecimal promoValue = row.promoItemValue();
    if (isPercentagePromo(row, activityTotal, discount)) {
      if (promoValue != null
          && promoValue.compareTo(BigDecimal.ZERO) > 0
          && promoValue.compareTo(BigDecimal.valueOf(100)) <= 0) {
        return promoValue;
      }
      if (activityTotal.signum() > 0 && discount.signum() > 0) {
        return discount
            .multiply(BigDecimal.valueOf(100))
            .divide(activityTotal, 2, RoundingMode.HALF_UP);
      }
      return BigDecimal.ZERO;
    }
    if (promoValue != null && promoValue.compareTo(BigDecimal.ZERO) > 0) {
      return promoValue;
    }
    return discount;
  }

  private boolean isPercentagePromo(
      PromoCodesByTransactionDateReportRow row, BigDecimal activityTotal, BigDecimal discount) {
    if ("PERCENT".equalsIgnoreCase(nullToBlank(row.giftCertificateType()))) {
      return true;
    }
    if (discount.signum() <= 0) {
      return false;
    }

    BigDecimal promoValue = row.promoItemValue();
    if (promoValue == null || promoValue.compareTo(BigDecimal.ZERO) <= 0) {
      return activityTotal.signum() > 0;
    }

    if (promoValue.compareTo(BigDecimal.valueOf(100)) > 0) {
      return false;
    }

    if (activityTotal.signum() <= 0) {
      return true;
    }

    BigDecimal percentageDiscount =
        activityTotal
            .multiply(promoValue)
            .divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP);
    if (percentageDiscount.subtract(discount).abs().compareTo(new BigDecimal("0.01")) <= 0) {
      return true;
    }

    return promoValue.subtract(discount).abs().compareTo(new BigDecimal("0.01")) > 0;
  }

  private BigDecimal allocatedDiscount(PromoCodesByTransactionDateReportRow row) {
    BigDecimal bookingDiscount = nullToZero(row.bookingDiscount());
    BigDecimal totalPaid = nullToZero(row.bookingTotalPaidPrice());
    BigDecimal eventSubtotal = nullToZero(row.eventSubtotal());
    if (bookingDiscount.signum() == 0 || totalPaid.signum() == 0) {
      return BigDecimal.ZERO;
    }
    return bookingDiscount
        .multiply(eventSubtotal)
        .divide(totalPaid, 2, RoundingMode.HALF_UP);
  }

  private LocalTime parseEventTime(String eventTime) {
    if (eventTime == null || eventTime.isBlank()) {
      return LocalTime.MIDNIGHT;
    }
    String normalized = eventTime.trim();
    String upperNormalized = normalized.toUpperCase(Locale.ENGLISH);
    for (DateTimeFormatter formatter :
        List.of(
            DateTimeFormatter.ofPattern("H:mm"),
            DateTimeFormatter.ofPattern("HH:mm"),
            DateTimeFormatter.ofPattern("h:mma", Locale.ENGLISH),
            DateTimeFormatter.ofPattern("h:mm a", Locale.ENGLISH))) {
      try {
        return LocalTime.parse(upperNormalized, formatter);
      } catch (DateTimeParseException ignored) {
        // try next pattern
      }
    }
    if (normalized.length() >= 5) {
      return LocalTime.parse(normalized.substring(0, 5));
    }
    return LocalTime.parse(normalized);
  }

  private void setTextCell(Row row, int columnIndex, String value) {
    if (value == null || value.isBlank()) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex).setCellValue(value);
  }

  private void setMoneyCell(Row row, int columnIndex, BigDecimal value) {
    row.createCell(columnIndex).setCellValue(nullToZero(value).doubleValue());
  }

  private void setDateCell(Row row, int columnIndex, LocalDate value) {
    if (value == null) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex).setCellValue(value.format(REPORT_DAY_FORMAT));
  }

  private void setTransactionDateTimeCell(Row row, int columnIndex, ZonedDateTime value) {
    if (value == null) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex)
        .setCellValue(
            value.withZoneSameInstant(REPORT_ZONE).toLocalDateTime().format(TRANSACTION_DATE_TIME_FORMAT));
  }

  private BigDecimal nullToZero(BigDecimal value) {
    return value == null ? BigDecimal.ZERO : value;
  }

  private static String nullToBlank(String value) {
    return value == null ? "" : value;
  }

  private static String nullToBlank(String value, String fallback) {
    if (value != null && !value.isBlank()) {
      return value;
    }
    return fallback == null ? "" : fallback;
  }

  private static final class PromoTotals {
    private final List<String> ticketTypeNames;
    private final Map<String, Integer> passengersByTicketType = new LinkedHashMap<>();
    private BigDecimal discount = BigDecimal.ZERO;

    private PromoTotals(List<String> ticketTypeNames) {
      this.ticketTypeNames = ticketTypeNames;
    }

    private void add(
        List<ReportDataRepository.TicketQuantityRow> ticketRows, BigDecimal rowDiscount) {
      TicketTypePassengerColumns.addToTotals(passengersByTicketType, ticketTypeNames, ticketRows);
      discount = discount.add(rowDiscount);
    }
  }
}
