package com.example.report.excel;

import com.example.exception.general.FileOperationException;
import com.example.model.record.UnredeemedGiftCertificateCodesReportRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

@Component
public class UnredeemedGiftCertificateCodesExcelBuilder {
  private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Hong_Kong");

  private static final DateTimeFormatter REPORT_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEEE, MMM dd yyyy", Locale.ENGLISH);

  private static final DateTimeFormatter DAY_FORMAT = DateTimeFormatter.ofPattern("dd/MM/yyyy");

  private static final DateTimeFormatter DATE_TIME_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
  private static final DateTimeFormatter REPORT_GENERATED_ON_FORMAT =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

  private static final String[] HEADERS = {
    "Type",
    "GC ID",
    "Online Code",
    "Status",
    "Wholesale Value",
    "Retail Value",
    "Date Issued",
    "Expiry",
    "Redemption Date",
    "Purchaser Name",
    "Description",
    "Sub-Total",
    "Total",
    "Discounts",
    "Net Total",
    "Balance"
  };

  public byte[] build(
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      List<UnredeemedGiftCertificateCodesReportRow> rows) {
    try (Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
      String sheetName =
          startDate + "-Report-" + UUID.randomUUID().toString().replace("-", "").substring(0, 13);
      Sheet sheet = workbook.createSheet(sheetName.substring(0, Math.min(sheetName.length(), 31)));

      ZonedDateTime generatedAt = ZonedDateTime.now(REPORT_ZONE);
      int rowIndex = writeMetadata(sheet, startDate, endDate, generatedBy, generatedAt);

      writeHeaderRow(sheet, rowIndex++);

      BigDecimal totalWholesale = BigDecimal.ZERO;
      BigDecimal totalRetail = BigDecimal.ZERO;
      BigDecimal totalSubTotal = BigDecimal.ZERO;
      BigDecimal totalTotal = BigDecimal.ZERO;
      BigDecimal totalDiscounts = BigDecimal.ZERO;
      BigDecimal totalNetTotal = BigDecimal.ZERO;
      BigDecimal totalBalance = BigDecimal.ZERO;
      for (UnredeemedGiftCertificateCodesReportRow row : rows) {
        writeDataRow(sheet, rowIndex++, row);
        BigDecimal wholesale = nullToZero(row.wholesaleValue());
        totalWholesale = totalWholesale.add(wholesale);
        totalRetail = totalRetail.add(nullToZero(row.retailValue()));
        totalSubTotal = totalSubTotal.add(wholesale);
        totalTotal = totalTotal.add(wholesale);
        totalNetTotal = totalNetTotal.add(wholesale);
        totalBalance = totalBalance.add(nullToZero(row.balance()));
      }

      writeTotalRow(
          sheet,
          rowIndex,
          totalWholesale,
          totalRetail,
          totalSubTotal,
          totalTotal,
          totalDiscounts,
          totalNetTotal,
          totalBalance);

      for (int columnIndex = 0; columnIndex < HEADERS.length; columnIndex++) {
        sheet.autoSizeColumn(columnIndex);
      }

      workbook.write(outputStream);
      return outputStream.toByteArray();
    } catch (IOException e) {
      throw new FileOperationException("Failed to generate unredeemed gift certificate codes report");
    }
  }

  private int writeMetadata(
      Sheet sheet,
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      ZonedDateTime generatedAt) {
    int row = 2;
    createValueRow(sheet, row++, "ALL UNREDEEMED GIFT CERTIFICATES");
    row++;
    createValueRow(sheet, row++, "Report Start Date:");
    createValueRow(sheet, row++, startDate.format(REPORT_DATE_FORMAT));
    createValueRow(sheet, row++, "Report End Date:");
    createValueRow(sheet, row++, endDate.format(REPORT_DATE_FORMAT));
    createValueRow(sheet, row++, "Report Generated On:");
    createValueRow(
        sheet, row++, generatedAt.withZoneSameInstant(REPORT_ZONE).format(REPORT_GENERATED_ON_FORMAT));
    createValueRow(sheet, row++, "Generated By:");
    createValueRow(sheet, row++, generatedBy != null ? generatedBy : "System");
    row++;
    return row;
  }

  private void writeHeaderRow(Sheet sheet, int rowIndex) {
    Row row = sheet.createRow(rowIndex);
    for (int i = 0; i < HEADERS.length; i++) {
      row.createCell(i).setCellValue(HEADERS[i]);
    }
    ReportExcelStyles.applyGreyToEntireRow(row, HEADERS.length, true);
  }

  private void writeDataRow(Sheet sheet, int rowIndex, UnredeemedGiftCertificateCodesReportRow row) {
    Row excelRow = sheet.createRow(rowIndex);
    BigDecimal wholesale = nullToZero(row.wholesaleValue());

    excelRow.createCell(0).setCellValue(row.typeLabel());
    excelRow.createCell(1).setCellValue(row.giftCertificateRefNo());
    excelRow.createCell(2).setCellValue(row.promoCode());
    excelRow.createCell(3).setCellValue(row.statusLabel());
    setNumericCell(excelRow.createCell(4), row.wholesaleValue());
    setNumericCell(excelRow.createCell(5), row.retailValue());
    if (row.dateIssued() != null) {
      excelRow
          .createCell(6)
          .setCellValue(row.dateIssued().withZoneSameInstant(REPORT_ZONE).format(DATE_TIME_FORMAT));
    }
    if (row.expiryDate() != null) {
      excelRow.createCell(7).setCellValue(row.expiryDate().format(DAY_FORMAT));
    }
    if (row.purchaserName() != null && !row.purchaserName().isBlank()) {
      excelRow.createCell(9).setCellValue(row.purchaserName());
    }
    if (row.description() != null) {
      excelRow.createCell(10).setCellValue(row.description());
    }
    setNumericCell(excelRow.createCell(11), wholesale);
    setNumericCell(excelRow.createCell(12), wholesale);
    setNumericCell(excelRow.createCell(13), BigDecimal.ZERO);
    setNumericCell(excelRow.createCell(14), wholesale);
    setNumericCell(excelRow.createCell(15), row.balance());
  }

  private void writeTotalRow(
      Sheet sheet,
      int rowIndex,
      BigDecimal totalWholesale,
      BigDecimal totalRetail,
      BigDecimal totalSubTotal,
      BigDecimal totalTotal,
      BigDecimal totalDiscounts,
      BigDecimal totalNetTotal,
      BigDecimal totalBalance) {
    Row row = sheet.createRow(rowIndex);
    setNumericCell(row.createCell(4), totalWholesale);
    setNumericCell(row.createCell(5), totalRetail);
    setNumericCell(row.createCell(11), totalSubTotal);
    setNumericCell(row.createCell(12), totalTotal);
    setNumericCell(row.createCell(13), totalDiscounts);
    setNumericCell(row.createCell(14), totalNetTotal);
    setNumericCell(row.createCell(15), totalBalance);
    ReportExcelStyles.applyGreyToEntireRow(row, HEADERS.length, true);
  }

  private void createValueRow(Sheet sheet, int rowIndex, String value) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue(value);
    ReportExcelStyles.applyGreyToEntireRow(row, HEADERS.length, false);
  }

  private void setNumericCell(Cell cell, BigDecimal value) {
    if (value != null) {
      cell.setCellValue(value.doubleValue());
    }
  }

  private BigDecimal nullToZero(BigDecimal value) {
    return value != null ? value : BigDecimal.ZERO;
  }
}
