package com.example.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GenerateBookingsByActivityDateReportRequestDTO {
    @NotNull
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @JsonProperty("start_date")
    @Schema(description = "Activity date range start (inclusive)", example = "2026-06-10")
    private LocalDate startDate;

    @NotNull
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @JsonProperty("end_date")
    @Schema(description = "Activity date range end (inclusive)", example = "2026-06-10")
    private LocalDate endDate;

    @JsonProperty("generated_by")
    @Schema(description = "Name shown in the Generated By row", example = "Manager")
    private String generatedBy;
}
