package com.example.model.dto;

import com.example.constant.Enums;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GenerateReportRequestDTO {
  @NotNull
  @JsonProperty("report_type")
  @Schema(
      description = "Report type to generate",
      example = "BOOKINGS_BY_ACTIVITY_DATE",
      allowableValues = {
        "BOOKINGS_BY_ACTIVITY_DATE",
        "BOOKINGS_BY_PURCHASE_DATE",
        "PROMO_CODES_BY_TRANSACTION_DATE",
        "COUNTRY_OF_ORIGIN",
        "EXPIRED_GIFT_CERTIFICATE_CODES",
        "REDEEMED_GIFT_CERTIFICATE_CODES"
      })
  private Enums.ReportType reportType;

  @NotNull
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
  @JsonProperty("start_date")
  @Schema(description = "Report date range start (inclusive)", example = "2026-06-10")
  private LocalDate startDate;

  @NotNull
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
  @JsonProperty("end_date")
  @Schema(description = "Report date range end (inclusive)", example = "2026-06-10")
  private LocalDate endDate;

  @JsonProperty("generated_by")
  @Schema(description = "Name shown in the Generated By row", example = "Manager")
  private String generatedBy;
}
