package com.example.service;

import com.example.exception.general.FileOperationException;
import com.example.model.record.BookingsByActivityDateReportRow;
import com.example.repository.ReportDataRepository;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;

@Component
public class BookingsByActivityDateExcelBuilder {
  private static final String DEFAULT_COMPANY = "Hong Kong Tramways";
  private static final String INTERNET_USER = "Internet User";
  private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Hong_Kong");

  private static final DateTimeFormatter REPORT_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEEE, MMM d yyyy", Locale.ENGLISH);
  private static final DateTimeFormatter REPORT_DAY_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy");
  private static final DateTimeFormatter REPORT_TIME_FORMAT =
      DateTimeFormatter.ofPattern("HH:mm:ss");
  private static final String[] ACTIVITY_HEADERS = {
    "Booking No.",
    "Activity",
    "Category",
    "Date",
    "Time",
    "Purchase Date",
    "Days to Purchase",
    "Company Type",
    "Company Group",
    "Booked by (Company)",
    "Booked by (User)",
    "Activity Provider",
    "Guest",
    "Country",
    "Passengers",
    "Subtotal",
    "Discount(s)",
    "Net Sale",
    "Total"
  };

  public byte[] build(
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      List<BookingsByActivityDateReportRow> rows,
      Map<Long, List<ReportDataRepository.TicketQuantityRow>> ticketQuantitiesByBookingEventId) {
    try (Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
      String sheetName =
          startDate + "-Report-" + UUID.randomUUID().toString().replace("-", "").substring(0, 13);
      Sheet sheet = workbook.createSheet(sheetName.substring(0, Math.min(sheetName.length(), 31)));

      ZonedDateTime generatedAt = ZonedDateTime.now(REPORT_ZONE);
      writeMetadata(sheet, startDate, endDate, generatedBy, generatedAt);

      int headerRowIndex = 18;
      writeActivityHeaderRow(sheet, headerRowIndex);

      int rowIndex = headerRowIndex + 1;
      ActivityTotals totals = new ActivityTotals();

      for (BookingsByActivityDateReportRow row : rows) {
        List<ReportDataRepository.TicketQuantityRow> ticketRows =
            ticketQuantitiesByBookingEventId.getOrDefault(row.bookingEventId(), List.of());
        writeActivityDataRow(sheet, rowIndex++, row, ticketRows, totals);
      }

      writeActivityTotalRow(sheet, rowIndex++, totals);

      for (int columnIndex = 0; columnIndex < ACTIVITY_HEADERS.length; columnIndex++) {
        sheet.autoSizeColumn(columnIndex);
      }

      workbook.write(outputStream);
      return outputStream.toByteArray();
    } catch (IOException e) {
      throw new FileOperationException("Failed to generate bookings by activity date report");
    }
  }

  private void writeMetadata(
      Sheet sheet,
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      ZonedDateTime generatedAt) {
    int row = 2;
    createLabelValueRow(sheet, row++, "ALL INTERNET BOOKINGS BY ACTIVITY DATE", null);
    row++;
    createLabelValueRow(sheet, row++, "Report Start Date:", startDate.format(REPORT_DATE_FORMAT));
    createLabelValueRow(sheet, row++, "Report End Date:", endDate.format(REPORT_DATE_FORMAT));
    createLabelValueRow(
        sheet, row++, "Report Generated On:", generatedAt.toLocalDateTime().toString());
    createLabelValueRow(
        sheet, row++, "Generated By:", generatedBy != null ? generatedBy : "System");
    row++;
    createLabelValueRow(sheet, row++, "Download Excel Download CSV", null);
    row++;
    createLabelValueRow(
        sheet,
        row++,
        "*Passenger Legend Seniors/Adult//Child (4-11)/",
        null);
    row++;
    createLabelValueRow(sheet, row++, "Activity Summary", null);
  }

  private void writeActivityHeaderRow(Sheet sheet, int rowIndex) {
    Row row = sheet.createRow(rowIndex);
    for (int i = 0; i < ACTIVITY_HEADERS.length; i++) {
      Cell cell = row.createCell(i);
      cell.setCellValue(ACTIVITY_HEADERS[i]);
    }
  }

  private void writeActivityDataRow(
      Sheet sheet,
      int rowIndex,
      BookingsByActivityDateReportRow row,
      List<ReportDataRepository.TicketQuantityRow> ticketRows,
      ActivityTotals totals) {
    BigDecimal subtotal = nullToZero(row.eventSubtotal());
    BigDecimal discount = allocatedDiscount(row);
    BigDecimal netSale = subtotal.subtract(discount);
    BigDecimal total = netSale;
    BigDecimal daysToPurchase = BigDecimal.valueOf(daysToPurchase(row));

    Row excelRow = sheet.createRow(rowIndex);
    int column = 0;
    setTextCell(excelRow, column++, row.bookingRefNo());
    excelRow.createCell(column++).setCellValue(formatEventName(row));
    excelRow.createCell(column++).setCellValue(nullToBlank(row.eventCategory()));
    setDateCell(excelRow, column++, row.eventDate());
    setTimeCell(excelRow, column++, row.eventTime());
    setPurchaseDateCell(excelRow, column++, row.purchaseDate());
    excelRow.createCell(column++).setCellValue(daysToPurchase.doubleValue());
    excelRow.createCell(column++).setCellValue(resolveCompanyType(row));
    excelRow.createCell(column++).setCellValue(resolveCompanyGroup(row));
    excelRow.createCell(column++).setCellValue(resolveBookedByCompany(row));
    excelRow.createCell(column++).setCellValue(resolveBookedByUser(row));
    excelRow.createCell(column++).setCellValue(resolveActivityProvider(row));
    excelRow.createCell(column++).setCellValue(formatGuestName(row));
    excelRow.createCell(column++).setCellValue(nullToBlank(row.guestCountry()));
    excelRow.createCell(column++).setCellValue(countPassengers(ticketRows));
    setMoneyCell(excelRow, column++, subtotal);
    setMoneyCell(excelRow, column++, discount);
    setMoneyCell(excelRow, column++, netSale);
    setMoneyCell(excelRow, column++, total);

    totals.add(daysToPurchase, ticketRows, subtotal, discount, netSale, total);
  }

  private void writeActivityTotalRow(Sheet sheet, int rowIndex, ActivityTotals totals) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue("Total");
    row.createCell(6).setCellValue("Avg: " + totals.averageDaysToPurchase());
    row.createCell(14).setCellValue(totals.totalPassengers);
    setMoneyCell(row, 15, totals.subtotal);
    setMoneyCell(row, 16, totals.discount);
    setMoneyCell(row, 17, totals.netSale);
    setMoneyCell(row, 18, totals.total);

    Row medianRow = sheet.createRow(rowIndex + 1);
    medianRow.createCell(6).setCellValue("Median: " + totals.medianDaysToPurchase());
  }

  private void createLabelValueRow(Sheet sheet, int rowIndex, String label, String value) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue(label);
    if (value != null) {
      row.createCell(1).setCellValue(value);
    }
  }

  private String formatEventName(BookingsByActivityDateReportRow row) {
    return nullToBlank(row.eventNameZhHk(), row.eventName());
  }

  private String formatGuestName(BookingsByActivityDateReportRow row) {
    String firstName = nullToBlank(row.guestFirstName());
    String lastName = nullToBlank(row.guestLastName());
    return (firstName + " " + lastName).trim();
  }

  private boolean isAgentBooking(BookingsByActivityDateReportRow row) {
    return row.userRole() != null && "AGENT".equalsIgnoreCase(row.userRole());
  }

  private boolean isUserBooking(BookingsByActivityDateReportRow row) {
    return row.userRole() == null || "USER".equalsIgnoreCase(row.userRole());
  }

  private boolean isEmployeeOrAdminBooking(BookingsByActivityDateReportRow row) {
    return row.userRole() != null
        && ("EMPLOYEE".equalsIgnoreCase(row.userRole())
            || "ADMIN".equalsIgnoreCase(row.userRole()));
  }

  private String resolveCompanyType(BookingsByActivityDateReportRow row) {
    return isAgentBooking(row) ? nullToBlank(row.companyType()) : "";
  }

  private String resolveCompanyGroup(BookingsByActivityDateReportRow row) {
    return isAgentBooking(row) ? nullToBlank(row.companyGroup()) : "";
  }

  private String resolveBookedByCompany(BookingsByActivityDateReportRow row) {
    if (isAgentBooking(row)) {
      return nullToBlank(row.organizationName(), DEFAULT_COMPANY);
    }
    if (isEmployeeOrAdminBooking(row)) {
      return DEFAULT_COMPANY;
    }
    return "";
  }

  private String resolveActivityProvider(BookingsByActivityDateReportRow row) {
    return DEFAULT_COMPANY;
  }

  private String resolveBookedByUser(BookingsByActivityDateReportRow row) {
    if (isUserBooking(row)) {
      return INTERNET_USER;
    }
    String firstName = nullToBlank(row.userFirstName());
    String lastName = nullToBlank(row.userLastName());
    String fullName = (firstName + " " + lastName).trim();
    return fullName.isBlank() ? INTERNET_USER : fullName;
  }

  private double daysToPurchase(BookingsByActivityDateReportRow row) {
    if (row.purchaseDate() == null || row.eventDate() == null) {
      return 0;
    }
    ZonedDateTime purchase = row.purchaseDate().withZoneSameInstant(REPORT_ZONE);
    ZonedDateTime activity =
        LocalDateTime.of(row.eventDate(), parseEventTime(row.eventTime()))
            .atZone(REPORT_ZONE);
    long minutes = Duration.between(purchase, activity).toMinutes();
    return Math.round(minutes / (24.0 * 60.0) * 100.0) / 100.0;
  }

  private BigDecimal allocatedDiscount(BookingsByActivityDateReportRow row) {
    BigDecimal bookingDiscount = nullToZero(row.bookingDiscount());
    BigDecimal totalPaid = nullToZero(row.bookingTotalPaidPrice());
    BigDecimal eventSubtotal = nullToZero(row.eventSubtotal());
    if (bookingDiscount.signum() == 0 || totalPaid.signum() == 0) {
      return BigDecimal.ZERO;
    }
    return bookingDiscount
        .multiply(eventSubtotal)
        .divide(totalPaid, 2, RoundingMode.HALF_UP);
  }

  private static int countPassengers(List<ReportDataRepository.TicketQuantityRow> ticketRows) {
    return ticketRows.stream().mapToInt(ReportDataRepository.TicketQuantityRow::quantity).sum();
  }

  private LocalTime parseEventTime(String eventTime) {
    if (eventTime == null || eventTime.isBlank()) {
      return LocalTime.MIDNIGHT;
    }
    String normalized = eventTime.trim();
    String upperNormalized = normalized.toUpperCase(Locale.ENGLISH);
    for (DateTimeFormatter formatter :
        List.of(
            DateTimeFormatter.ofPattern("H:mm"),
            DateTimeFormatter.ofPattern("HH:mm"),
            DateTimeFormatter.ofPattern("h:mma", Locale.ENGLISH),
            DateTimeFormatter.ofPattern("h:mm a", Locale.ENGLISH))) {
      try {
        return LocalTime.parse(upperNormalized, formatter);
      } catch (DateTimeParseException ignored) {
        // try next pattern
      }
    }
    if (normalized.length() >= 5) {
      return LocalTime.parse(normalized.substring(0, 5));
    }
    return LocalTime.parse(normalized);
  }

  private void setTextCell(Row row, int columnIndex, String value) {
    if (value == null || value.isBlank()) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex).setCellValue(value);
  }

  private void setMoneyCell(Row row, int columnIndex, BigDecimal value) {
    row.createCell(columnIndex).setCellValue(nullToZero(value).doubleValue());
  }

  private void setDateCell(Row row, int columnIndex, LocalDate value) {
    if (value == null) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex).setCellValue(value.format(REPORT_DAY_FORMAT));
  }

  private void setTimeCell(Row row, int columnIndex, String eventTime) {
    row.createCell(columnIndex).setCellValue(parseEventTime(eventTime).format(REPORT_TIME_FORMAT));
  }

  private void setPurchaseDateCell(Row row, int columnIndex, ZonedDateTime value) {
    if (value == null) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex)
        .setCellValue(value.withZoneSameInstant(REPORT_ZONE).toLocalDate().format(REPORT_DAY_FORMAT));
  }

  private BigDecimal nullToZero(BigDecimal value) {
    return value == null ? BigDecimal.ZERO : value;
  }

  private static String nullToBlank(String value) {
    return value == null ? "" : value;
  }

  private static String nullToBlank(String value, String fallback) {
    if (value != null && !value.isBlank()) {
      return value;
    }
    return fallback == null ? "" : fallback;
  }

  private static final class ActivityTotals {
    private final List<BigDecimal> daysToPurchaseValues = new ArrayList<>();
    private int totalPassengers = 0;
    private BigDecimal subtotal = BigDecimal.ZERO;
    private BigDecimal discount = BigDecimal.ZERO;
    private BigDecimal netSale = BigDecimal.ZERO;
    private BigDecimal total = BigDecimal.ZERO;

    private void add(
        BigDecimal daysToPurchase,
        List<ReportDataRepository.TicketQuantityRow> ticketRows,
        BigDecimal rowSubtotal,
        BigDecimal rowDiscount,
        BigDecimal rowNetSale,
        BigDecimal rowTotal) {
      daysToPurchaseValues.add(daysToPurchase);
      totalPassengers += countPassengers(ticketRows);
      subtotal = subtotal.add(rowSubtotal);
      discount = discount.add(rowDiscount);
      netSale = netSale.add(rowNetSale);
      total = total.add(rowTotal);
    }

    private String averageDaysToPurchase() {
      if (daysToPurchaseValues.isEmpty()) {
        return "0";
      }
      BigDecimal sum = daysToPurchaseValues.stream().reduce(BigDecimal.ZERO, BigDecimal::add);
      return sum.divide(BigDecimal.valueOf(daysToPurchaseValues.size()), 2, RoundingMode.HALF_UP)
          .stripTrailingZeros()
          .toPlainString();
    }

    private String medianDaysToPurchase() {
      if (daysToPurchaseValues.isEmpty()) {
        return "0";
      }
      List<BigDecimal> sorted = new ArrayList<>(daysToPurchaseValues);
      sorted.sort(Comparator.naturalOrder());
      int middle = sorted.size() / 2;
      if (sorted.size() % 2 == 0) {
        return sorted
            .get(middle - 1)
            .add(sorted.get(middle))
            .divide(BigDecimal.valueOf(2), 0, RoundingMode.HALF_UP)
            .stripTrailingZeros()
            .toPlainString();
      }
      return sorted.get(middle).setScale(0, RoundingMode.HALF_UP).stripTrailingZeros().toPlainString();
    }
  }
}
