package com.example.service;

import com.example.exception.general.FileOperationException;
import com.example.model.record.PromoCodesByTransactionDateReportRow;
import com.example.repository.ReportDataRepository;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;

@Component
public class PromoCodesByTransactionDateExcelBuilder {
  private static final String DEFAULT_ACTIVITY_PROVIDER = "Hong Kong Tramways";
  private static final ZoneId REPORT_ZONE = ZoneId.of("Asia/Hong_Kong");

  private static final DateTimeFormatter REPORT_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEEE, MMM d yyyy", Locale.ENGLISH);
  private static final DateTimeFormatter REPORT_DAY_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy");
  private static final DateTimeFormatter TRANSACTION_DATE_TIME_FORMAT =
      DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
  private static final DateTimeFormatter ACTIVITY_TIME_FORMAT =
      DateTimeFormatter.ofPattern("h:mma", Locale.ENGLISH);

  private static final String[] HEADERS = {
    "Conf.#",
    "Transaction Date/Time",
    "Activity Date",
    "Activity Name",
    "Guest Name",
    "Passengers",
    "Activity Total",
    "Activity Provider",
    "Product Name",
    "Promo Name",
    "Promo Rate Type",
    "Promo Rate",
    "Discount($)"
  };

  public byte[] build(
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      List<PromoCodesByTransactionDateReportRow> rows,
      Map<Long, List<ReportDataRepository.TicketQuantityRow>> ticketQuantitiesByBookingEventId) {
    try (Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
      String sheetName =
          startDate + "-Promo-" + UUID.randomUUID().toString().replace("-", "").substring(0, 10);
      Sheet sheet = workbook.createSheet(sheetName.substring(0, Math.min(sheetName.length(), 31)));

      ZonedDateTime generatedAt = ZonedDateTime.now(REPORT_ZONE);
      writeMetadata(sheet, startDate, endDate, generatedBy, generatedAt);

      int headerRowIndex = 18;
      writeHeaderRow(sheet, headerRowIndex);

      int rowIndex = headerRowIndex + 1;
      PromoTotals totals = new PromoTotals();

      for (PromoCodesByTransactionDateReportRow row : rows) {
        List<ReportDataRepository.TicketQuantityRow> ticketRows =
            ticketQuantitiesByBookingEventId.getOrDefault(row.bookingEventId(), List.of());
        writeDataRow(sheet, rowIndex++, row, ticketRows, totals);
      }

      writeTotalRow(sheet, rowIndex, totals);

      for (int columnIndex = 0; columnIndex < HEADERS.length; columnIndex++) {
        sheet.autoSizeColumn(columnIndex);
      }

      workbook.write(outputStream);
      return outputStream.toByteArray();
    } catch (IOException e) {
      throw new FileOperationException("Failed to generate promo codes by transaction date report");
    }
  }

  private void writeMetadata(
      Sheet sheet,
      LocalDate startDate,
      LocalDate endDate,
      String generatedBy,
      ZonedDateTime generatedAt) {
    int row = 2;
    createLabelValueRow(sheet, row++, "PROMO CODES BY TRANSACTION DATE", null);
    row++;
    createLabelValueRow(sheet, row++, "Report Start Date:", startDate.format(REPORT_DATE_FORMAT));
    createLabelValueRow(sheet, row++, "Report End Date:", endDate.format(REPORT_DATE_FORMAT));
    createLabelValueRow(
        sheet, row++, "Report Generated On:", generatedAt.toLocalDateTime().toString());
    createLabelValueRow(
        sheet, row++, "Generated By:", generatedBy != null ? generatedBy : "System");
    row++;
    createLabelValueRow(sheet, row++, "Download Excel Download CSV", null);
  }

  private void writeHeaderRow(Sheet sheet, int rowIndex) {
    Row row = sheet.createRow(rowIndex);
    for (int i = 0; i < HEADERS.length; i++) {
      row.createCell(i).setCellValue(HEADERS[i]);
    }
  }

  private void writeDataRow(
      Sheet sheet,
      int rowIndex,
      PromoCodesByTransactionDateReportRow row,
      List<ReportDataRepository.TicketQuantityRow> ticketRows,
      PromoTotals totals) {
    BigDecimal activityTotal = nullToZero(row.eventSubtotal());
    BigDecimal discount = allocatedDiscount(row);
    int passengers = countPassengers(ticketRows);

    Row excelRow = sheet.createRow(rowIndex);
    int column = 0;
    setTextCell(excelRow, column++, row.bookingRefNo());
    setTransactionDateTimeCell(excelRow, column++, row.transactionDateTime());
    setDateCell(excelRow, column++, row.eventDate());
    excelRow.createCell(column++).setCellValue(formatActivityName(row));
    excelRow.createCell(column++).setCellValue(formatGuestName(row));
    excelRow.createCell(column++).setCellValue(passengers);
    setMoneyCell(excelRow, column++, activityTotal);
    excelRow.createCell(column++).setCellValue(DEFAULT_ACTIVITY_PROVIDER);
    excelRow.createCell(column++).setBlank();
    excelRow.createCell(column++).setCellValue(nullToBlank(row.promoCode()));
    excelRow.createCell(column++).setCellValue(resolvePromoRateType(row, activityTotal, discount));
    setMoneyCell(excelRow, column++, resolvePromoRate(row, activityTotal, discount));
    setMoneyCell(excelRow, column++, discount);

    totals.add(passengers, discount);
  }

  private void writeTotalRow(Sheet sheet, int rowIndex, PromoTotals totals) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue("Total");
    row.createCell(5).setCellValue(totals.totalPassengers);
    setMoneyCell(row, 12, totals.discount);
  }

  private void createLabelValueRow(Sheet sheet, int rowIndex, String label, String value) {
    Row row = sheet.createRow(rowIndex);
    row.createCell(0).setCellValue(label);
    if (value != null) {
      row.createCell(1).setCellValue(value);
    }
  }

  private String formatActivityName(PromoCodesByTransactionDateReportRow row) {
    String localizedName = nullToBlank(row.eventNameZhHk(), row.eventName());
    if (!localizedName.isBlank()) {
      return localizedName;
    }
    if (row.eventTime() == null || row.eventTime().isBlank()) {
      return "";
    }
    return parseEventTime(row.eventTime())
        .format(ACTIVITY_TIME_FORMAT)
        .toLowerCase(Locale.ENGLISH);
  }

  private String formatGuestName(PromoCodesByTransactionDateReportRow row) {
    String firstName = nullToBlank(row.guestFirstName());
    String lastName = nullToBlank(row.guestLastName());
    return (firstName + " " + lastName).trim();
  }

  private String resolvePromoRateType(
      PromoCodesByTransactionDateReportRow row, BigDecimal activityTotal, BigDecimal discount) {
    if (isValuePromo(row)) {
      return "Amount";
    }
    if (hasConfiguredPercentage(row)) {
      return "Percentage";
    }
    if (activityTotal.signum() > 0 && discount.signum() > 0) {
      return "Percentage";
    }
    return "Amount";
  }

  private BigDecimal resolvePromoRate(
      PromoCodesByTransactionDateReportRow row, BigDecimal activityTotal, BigDecimal discount) {
    if (isValuePromo(row)) {
      return row.promoItemValue() != null ? row.promoItemValue() : discount;
    }
    if (hasConfiguredPercentage(row)) {
      return row.promoItemValue();
    }
    if (activityTotal.signum() > 0 && discount.signum() > 0) {
      return discount
          .multiply(BigDecimal.valueOf(100))
          .divide(activityTotal, 2, RoundingMode.HALF_UP);
    }
    return BigDecimal.ZERO;
  }

  private boolean isValuePromo(PromoCodesByTransactionDateReportRow row) {
    String type = nullToBlank(row.giftCertificateType());
    return "VALUE".equalsIgnoreCase(type) || "PERSONAL_VALUE".equalsIgnoreCase(type);
  }

  private boolean hasConfiguredPercentage(PromoCodesByTransactionDateReportRow row) {
    return row.promoItemValue() != null
        && row.promoItemValue().compareTo(BigDecimal.ZERO) > 0
        && row.promoItemValue().compareTo(BigDecimal.valueOf(100)) <= 0;
  }

  private BigDecimal allocatedDiscount(PromoCodesByTransactionDateReportRow row) {
    BigDecimal bookingDiscount = nullToZero(row.bookingDiscount());
    BigDecimal totalPaid = nullToZero(row.bookingTotalPaidPrice());
    BigDecimal eventSubtotal = nullToZero(row.eventSubtotal());
    if (bookingDiscount.signum() == 0 || totalPaid.signum() == 0) {
      return BigDecimal.ZERO;
    }
    return bookingDiscount
        .multiply(eventSubtotal)
        .divide(totalPaid, 2, RoundingMode.HALF_UP);
  }

  private static int countPassengers(List<ReportDataRepository.TicketQuantityRow> ticketRows) {
    return ticketRows.stream().mapToInt(ReportDataRepository.TicketQuantityRow::quantity).sum();
  }

  private LocalTime parseEventTime(String eventTime) {
    if (eventTime == null || eventTime.isBlank()) {
      return LocalTime.MIDNIGHT;
    }
    String normalized = eventTime.trim();
    String upperNormalized = normalized.toUpperCase(Locale.ENGLISH);
    for (DateTimeFormatter formatter :
        List.of(
            DateTimeFormatter.ofPattern("H:mm"),
            DateTimeFormatter.ofPattern("HH:mm"),
            DateTimeFormatter.ofPattern("h:mma", Locale.ENGLISH),
            DateTimeFormatter.ofPattern("h:mm a", Locale.ENGLISH))) {
      try {
        return LocalTime.parse(upperNormalized, formatter);
      } catch (DateTimeParseException ignored) {
        // try next pattern
      }
    }
    if (normalized.length() >= 5) {
      return LocalTime.parse(normalized.substring(0, 5));
    }
    return LocalTime.parse(normalized);
  }

  private void setTextCell(Row row, int columnIndex, String value) {
    if (value == null || value.isBlank()) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex).setCellValue(value);
  }

  private void setMoneyCell(Row row, int columnIndex, BigDecimal value) {
    row.createCell(columnIndex).setCellValue(nullToZero(value).doubleValue());
  }

  private void setDateCell(Row row, int columnIndex, LocalDate value) {
    if (value == null) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex).setCellValue(value.format(REPORT_DAY_FORMAT));
  }

  private void setTransactionDateTimeCell(Row row, int columnIndex, ZonedDateTime value) {
    if (value == null) {
      row.createCell(columnIndex).setBlank();
      return;
    }
    row.createCell(columnIndex)
        .setCellValue(
            value.withZoneSameInstant(REPORT_ZONE).toLocalDateTime().format(TRANSACTION_DATE_TIME_FORMAT));
  }

  private BigDecimal nullToZero(BigDecimal value) {
    return value == null ? BigDecimal.ZERO : value;
  }

  private static String nullToBlank(String value) {
    return value == null ? "" : value;
  }

  private static String nullToBlank(String value, String fallback) {
    if (value != null && !value.isBlank()) {
      return value;
    }
    return fallback == null ? "" : fallback;
  }

  private static final class PromoTotals {
    private int totalPassengers = 0;
    private BigDecimal discount = BigDecimal.ZERO;

    private void add(int passengers, BigDecimal rowDiscount) {
      totalPassengers += passengers;
      discount = discount.add(rowDiscount);
    }
  }
}
